version: 2.1

jobs:
  static:
    docker:
      - image: lusy/alpine-php:latest
        auth:
          username: ppaulis
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Composer install
          command: |
            ./composer.phar install -n
      - run:
          name: PHPStan
          command: |
            mkdir -p results/PHPStan
            php -d memory_limit=4G vendor/bin/phpstan analyze module --level 7 --error-format=junit > results/PHPStan/result.xml; php -d memory_limit=4G vendor/bin/phpstan analyze module --level 7
      - run:
          name: PHPCS
          command: |
            mkdir -p results/PHPCS
            vendor/bin/phpcs module

workflows:
  version: 2
  build:
    jobs:
      - static
